version: '3'
services:


  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

  dispatcher:
    image: keymetrics/pm2:8
    volumes:
      - ${NGINX_FILES_PATH}/certs/${MAIN_DOMAIN}:/certs
      - ./dispatcher:/api
    working_dir: /api
    expose:
      - "443"
      - "80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - VIRTUAL_HOST=${MAIN_DOMAIN}
      - LETSENCRYPT_HOST=${MAIN_DOMAIN}
      - LETSENCRYPT_EMAIL=jean.cedric.t@gmail.com
      - NPM_CONFIG_LOGLEVEL=warn
    command: ["pm2-docker", "start", "pm2.json"]
    links:
      - event_bus
      - nginx-letsencrypt
    depends_on:
      - event_bus
      - nginx-letsencrypt

  commandHandlers:
    image: keymetrics/pm2:8
    volumes:
      - ./commandHandlers:/api
    working_dir: /api
    environment:
      - NODE_ENV=${NODE_ENV}
      - NPM_CONFIG_LOGLEVEL=warn
    command: ["pm2-docker", "start", "pm2.json"]
    links:
      - event_bus
      - db
    depends_on:
      - event_bus
      - db

# queryHandlers:
#   image: keymetrics/pm2:8
#   volumes:
#     - ./queryHandlers:/api
#   working_dir: /api
#   environment:
#     - NODE_ENV=${NODE_ENV}
#     - NPM_CONFIG_LOGLEVEL=warn
#   command: ["pm2-docker", "start", "pm2.json"]
#   links:
#     - event_bus
#     - db
#   depends_on:
#     - event_bus
#     - db


  db:
    image: mongo:3.4
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  event_bus:
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 8080:15672


networks:
  default:
    external:
      name: webproxy
