version: '2'
services:


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  dispatcher:
    image: kpr
    working_dir: /api
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=site.example.com
      - LETSENCRYPT_HOST=site.example.com
      - LETSENCRYPT_EMAIL=email@example.com
    links:
      - db
      - event_bus
    depends_on:
      - db
      - event_bus

  db:
    image: mongo:3.4
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  event_bus:
    image: rabbitmq:3.6-management
    ports:
      - 5672:5672
      - 8080:15672
